---
title: "Group Project_ver2"
author: "Bo Yun"
date: "9/26/2020"
output: html_document
---

```{r}
## Importing libraries
library(mvtnorm)
library(dplyr)
library(class)
library(tidyr)
library(tidyverse)
library(dplyr)
library(caret)
library(e1071)
library(qpcR)
library(ggplot2)
library(GGally)
library(ggplot2)
library(ggthemes)
library(gridExtra)
library(tidyverse)
library(plyr)
library(dplyr) 
library(naniar) #keep
library(zoo)
```

### Version 2 (All categorical removed & Thiness.5.9.years, GDP, under.five.deaths, Population removed) -------------

## Importing and Cleaning the Data
```{r,fig.height=6, fig.width=9,echo=FALSE,warning=FALSE,message=FALSE}
########### Loading the data
life_ex_DF <- read.csv("https://raw.githubusercontent.com/kristxh/Applied_Stats_Project1/master/datasets_12603_17232_Life_Expectancy_Data.csv")

# cleaning up column names
colnames(life_ex_DF) <- tolower(colnames(life_ex_DF))
colnames(life_ex_DF) <- gsub("\\.\\.",".",colnames(life_ex_DF))
colnames(life_ex_DF) <- gsub("\\.","_",colnames(life_ex_DF))
names(life_ex_DF)[19] <- "thinness_10_19_years"

# reviewing the structure of the data
str(life_ex_DF)
# converting status to factor column
life_ex_DF$country <- as.factor(life_ex_DF$country)
life_ex_DF$status <- as.factor(life_ex_DF$status)
life_ex_DF$year <- as.factor(life_ex_DF$year)

# checking for missing values in the data
vis_miss(life_ex_DF) + xlab("Data Columns")
```

## fix missing data
```{r, fig.height=9, fig.width=9}
# sorting the columns so that life_expectancy column is first
life_ex_DF <- life_ex_DF[,c(4,1:3, 5:22)]

factorcols <- c("status","country","year")
allcols <- colnames(life_ex_DF)

# selecting only numerical columns for correlation
corvars <-colnames(select_if(life_ex_DF, is.numeric))

# impute with median missing values per country
life_ex_median_DF <- as.data.frame(life_ex_DF %>%
                                     group_by(country) %>%
                                     mutate_at(corvars, na.aggregate, FUN=median))

# dropping rows where the country has a single entry/record in the dataset and their records are mostly incomplete
life_ex_median_DF <- life_ex_median_DF[!is.na(life_ex_median_DF$life_expectancy), ]

# imputing the median by country still left a few nulls throughout. We will then impute the rest of the missing values as the mean of stats (developing, developed, by year)
life_ex_cleaned_DF <- as.data.frame(life_ex_median_DF %>% group_by(status) %>%
                                      mutate_at(corvars, na.aggregate, FUN=median))

# Error occured when grouping by year
life_ex_cleaned_DF <- as.data.frame(life_ex_median_DF %>% group_by(year) %>%
                                      mutate_at(corvars, na.aggregate, FUN=median))

# checking for missing values in the data
vis_miss(life_ex_cleaned_DF) + xlab("Data Columns")

# summary of cleaned up data
summary(life_ex_cleaned_DF)
str(life_ex_cleaned_DF)

```


```{r}
Life <- life_ex_cleaned_DF

Life <- Life[,-c(2,12, 17, 18, 20)] # Removing "country" variable from being insignificant from the ANOVA result)

# MLR 
full.model1<-lm(life_expectancy~. ,data=Life)


# Checking residuals and q-q plot
par(mfrow=c(2,2))
plot(full.model1)



```


# Variable selection - Forward 
```{r}
# Just the training set
library(leaps)
reg.fwd=regsubsets(life_expectancy~.,data=Life,method="forward",nvmax=14)

par(mfrow=c(1,3))
bics<-summary(reg.fwd)$bic
plot(1:14,bics,type="l",ylab="BIC",xlab="# of predictors")
index<-which(bics==min(bics))
points(index,bics[index],col="red",pch=10)

adjr2<-summary(reg.fwd)$adjr2
plot(1:14,adjr2,type="l",ylab="Adjusted R-squared",xlab="# of predictors")
index<-which(adjr2==max(adjr2))
points(index,adjr2[index],col="red",pch=10)

rss<-summary(reg.fwd)$rss
plot(1:14,rss,type="l",ylab="train RSS",xlab="# of predictors")
index<-which(rss==min(rss))
points(index,rss[index],col="red",pch=10)

# Optimal # : -> 11 predictors 


# Cross Validation on Train vs Test 
# Splitting 2939 observations of the data into Training and Test set in the ratio of 70:30

set.seed(1234)
trainIndices = sample(seq(1:dim(Life)[1]),round(.7*dim(Life)[1]))
train = Life[trainIndices,]
test = Life[-trainIndices,]
dim(train)
dim(test)


reg.fwd2=regsubsets(life_expectancy~.,data=train,method="forward",nvmax=14)

predict.regsubsets =function (object , newdata ,id ,...){
  form=as.formula (object$call [[2]])
  mat=model.matrix(form ,newdata )
  coefi=coef(object ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi
}

testASE<-c()
#note my index is to 20 since that what I set it in regsubsets
for (i in 1:14){
  predictions2<-predict.regsubsets(object=reg.fwd2,newdata=test,id=i) 
  testASE[i]<-mean((test$life_expectancy-predictions2)^2)
}

par(mfrow=c(1,1))
plot(1:14,testASE,type="l",xlab="# of predictors",ylab="test vs train ASE",ylim=c(10,50))
index<-which(testASE==min(testASE))
points(index,testASE[index],col="red",pch=10)
rss<-summary(reg.fwd2)$rss
lines(1:14,rss/2928,lty=3,col="blue")  #Dividing by 2928 since ASE=RSS/sample size


reg.final=regsubsets(life_expectancy~.,data=Life,method="forward",nvmax=11)
coef(reg.final,10)

final.model1<-lm(life_expectancy~ status+adult_mortality+ percentage_expenditure +measles+bmi+polio+diphtheria+hiv_aids+income_composition_of_resources+  schooling, data=Life)
summary(final.model1)

plot(final.model1$fitted.values,Life$life_expectancy,xlab="Predicted",ylab="Life Expectancy",xlim=c(20,110),ylim=c(20,110) )
lines(c(20,110),c(20,110),col="red")

```


# Variable selection - Backward
```{r}
# Just the training set
library(leaps)
reg.bwd=regsubsets(life_expectancy~.,data=Life,method="backward",nvmax=14)

par(mfrow=c(1,3))
bics2<-summary(reg.bwd)$bic
plot(1:14,bics2,type="l",ylab="BIC",xlab="# of predictors")
index2<-which(bics2==min(bics2))
points(index2,bics2[index2],col="red",pch=10)

adjr2<-summary(reg.bwd)$adjr2
plot(1:14,adjr2,type="l",ylab="Adjusted R-squared",xlab="# of predictors")
index.r2<-which(adjr2==max(adjr2))
points(index.r2,adjr2[index.r2],col="red",pch=10)

rss2<-summary(reg.bwd)$rss
plot(1:14,rss2,type="l",ylab="train RSS",xlab="# of predictors")
index.rss2<-which(rss2==min(rss2))
points(index.rss2,rss[index.rss2],col="red",pch=10)

# -> 11 predictors


# Cross Validation on Train vs Test 
# Splitting 2939 observations of the data into Training and Test set in the ratio of 70:30


reg.bwd2=regsubsets(life_expectancy~.,data=train,method="backward",nvmax=14)

predict.regsubsets =function (object , newdata ,id ,...){
  form=as.formula (object$call [[2]])
  mat=model.matrix(form ,newdata )
  coefi=coef(object ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi
}

testASE2<-c()
#note my index is to 20 since that what I set it in regsubsets
for (i in 1:14){
  predictions3<-predict.regsubsets(object=reg.bwd2,newdata=test,id=i) 
  testASE2[i]<-mean((test$life_expectancy-predictions3)^2)
}

par(mfrow=c(1,1))
plot(1:14,testASE2,type="l",xlab="# of predictors",ylab="test vs train ASE",ylim=c(10,50))
index<-which(testASE2==min(testASE2))
points(index,testASE2[index],col="red",pch=10)
rss2<-summary(reg.bwd2)$rss
lines(1:14,rss2/2928,lty=3,col="blue")  #Dividing by 2928 since ASE=RSS/sample size


reg.final2=regsubsets(life_expectancy~. ,data=Life,method="backward",nvmax=11)
coef(reg.final2,10)

final.model2<-lm(life_expectancy~ status+adult_mortality+percentage_expenditure+measles+ bmi+ polio + diphtheria +hiv_aids+income_composition_of_resources+schooling,data=Life)
summary(final.model2)

plot(final.model2$fitted.values,Life$life_expectancy,xlab="Predicted",ylab="Life Expectancy",xlim=c(20,110),ylim=c(20,110))
lines(c(20,110),c(20,110),col="red")
```

# Variable selection - Stepwise
```{r}
# Just the training set
library(leaps)
reg.stp=regsubsets(life_expectancy~.,data=Life,method="seqrep",nvmax=14)

par(mfrow=c(1,3))
bics3<-summary(reg.stp)$bic
plot(1:14,bics,type="l",ylab="BIC",xlab="# of predictors")
index3<-which(bics3==min(bics3))
points(index3,bics[index3],col="red",pch=10)

adjr3<-summary(reg.stp)$adjr
plot(1:14,adjr3,type="l",ylab="Adjusted R-squared",xlab="# of predictors")
index3<-which(adjr3==max(adjr3))
points(index3,adjr3[index3],col="red",pch=10)


rss3<-summary(reg.stp)$rss
plot(1:14,rss3,type="l",ylab="train RSS",xlab="# of predictors")
index3<-which(rss3==min(rss3))
points(index3,rss[index3],col="red",pch=10)

# -> 11 predictors


# Cross Validation on Train vs Test 
# Splitting 2939 observations of the data into Training and Test set in the ratio of 70:30



reg.stp2=regsubsets(life_expectancy~.,data=train,method="seqrep",nvmax=14)

predict.regsubsets =function (object , newdata ,id ,...){
  form=as.formula (object$call [[2]])
  mat=model.matrix(form ,newdata )
  coefi=coef(object ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi
}

testASE4<-c()
#note my index is to 20 since that what I set it in regsubsets
for (i in 1:14){
  predictions4<-predict.regsubsets(object=reg.stp2,newdata=test,id=i) 
  testASE4[i]<-mean((test$life_expectancy-predictions4)^2)
}

par(mfrow=c(1,1))
plot(1:14,testASE4,type="l",xlab="# of predictors",ylab="test vs train ASE",ylim=c(10,50))
index<-which(testASE4==min(testASE4))
points(index,testASE4[index],col="red",pch=10)
rss3<-summary(reg.stp2)$rss3
lines(1:14,rss3/2928,lty=3,col="blue")  #Dividing by 2928 since ASE=RSS/sample size


reg.final3=regsubsets(life_expectancy~.,data=Life,method="seqrep",nvmax=11)
coef(reg.final3,10)
summary(reg.final3)


final.model3<-lm(life_expectancy~.-total_expenditure - hepatitis_b - alcohol -infant_deaths, data=Life)
summary(final.model3)

plot(final.model3$fitted.values,Life$life_expectancy,xlab="Predicted",ylab="Life Expectancy",xlim=c(20,110),ylim=c(20,110) )
lines(c(20,110),c(20,110),col="red")

```


# Variable selection - LASSO
```{r}
library(glmnet)
## Loading required package: Matrix
## Loading required package: foreach
## Loaded glmnet 2.0-13
#Formatting data for GLM net
x=model.matrix(life_expectancy~.,train)[,-1]
y=log(train$life_expectancy)

xtest<-model.matrix(life_expectancy~.,test)[,-1]
ytest<-log(test$life_expectancy)


grid=10^seq(10,-2, length =100)
lasso.mod=glmnet(x,y,alpha=1, lambda =grid)

cv.out=cv.glmnet(x,y,alpha=1) #alpha=1 performs LASSO
plot(cv.out)

bestlambda<-cv.out$lambda.min  #Optimal penalty parameter.  You can make this call visually.
lasso.pred=predict (lasso.mod ,s=bestlambda ,newx=xtest)

testMSE_LASSO<-mean((ytest-lasso.pred)^2)
testMSE_LASSO

coef(lasso.mod,s=bestlambda)

final.model5<-lm(life_expectancy~., data=Life)

final.model4<-lm(life_expectancy~.-infant_deaths  -alcohol - hepatitis_b -measles  -total_expenditure  , data=Life)
summary(final.model4)
summary(final.model5)
plot(final.model4$fitted.values,Life$life_expectancy,xlab="Predicted",ylab="Life Expectancy",xlim=c(20,110),ylim=c(20,110), na.rm = TRUE )
lines(c(20,110),c(20,110),col="red")
```



```{r}
#ASE = RMSE, AIC, BIC, Rsqr calculation and comparison of models

RMSE(final.model1)
RMSE(final.model2)
RMSE(final.model3)
RMSE(final.model4)
AIC(final.model1,final.model2, final.model3, final.model4)
BIC(final.model,final.model2, final.model3, final.model4)
rsq(final.model1)
rsq(final.model2)
rsq(final.model3)
rsq(final.model4)
```







